In [1]:
from keras_regression_extractive_summarizer import KerasRegressionExtractiveSummarizer

Using TensorFlow backend.


In [2]:
import numpy as np

In [3]:
summarizer = KerasRegressionExtractiveSummarizer()

loading embedding_model...
loading embedding_model...
loading similarity threshold data...
loading trained model: /Users/kiriyama.k.ab/Fujii.lab/story_modeling/model/narou/threshold_estimate_trained_model/180820/model_30_vloss0.0078.hdf5
loading data dict...
saving splited data ncode...
converting dict to tensor...
converting dict to tensor...
num of novels which is training data: 508
num of novels which is test data: 127
loading trained model: /Users/kiriyama.k.ab/Fujii.lab/story_modeling/model/narou/reg_trained_model/180817/model_26_vloss0.0058.hdf5


In [4]:
ncode = list(summarizer.data_dict.keys())[7]

In [5]:
data = summarizer.data_dict[ncode]

In [6]:
contents_lines = summarizer.corpus.get_contents_lines(ncode)

In [7]:
removed_contents_lines = np.array(summarizer.corpus.remove_error_line_indexes_from_contents_lines(contents_lines, data['error_line_indexes']))

In [8]:
synopsis_lines = summarizer.corpus.get_synopsis_lines(ncode)

In [9]:
positive_index = np.where(data['Y']==1)

In [10]:
negative_index = np.where(data['Y']==0)

In [11]:
positive_index

(array([ 8, 26, 65, 67]),)

In [12]:
negative_index

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52,
        53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 66, 68, 69, 70, 71]),)

In [13]:
ncode

'n1577ck'

In [14]:
synopsis_lines

['簡単に言えば旦那のことが大好きな奥さんの話ですよ。',
 '殺したいって言うのは一種の愛情表現だ。',
 'ただ度が過ぎると言う位だ。',
 'まあ、どのくらいかは見ておくんなまし。',
 '基本的には1話が2000文字以内の小説になります。']

In [15]:
removed_contents_lines[positive_index]

array(['でも、そんな妻のことが本当に大好きです。', '毎日数字ばっかり見ていて頭が痛くなってくるんだよな。',
       '簡単に言えば束縛ですね。', 'まぁ、嫌ではないんだけどちょっと度が過ぎるんだよな。'], dtype='<U211')

In [16]:
removed_contents_lines[negative_index]

array(['私は高校から社会人になって２年目に突入しました。', 'ちなみに旦那も同じ会社で働いています。',
       '結婚生活も２年目に突入しました。', 'そんな旦那を私は殺したいほど本当に愛しています。',
       '―――――――――――――――ぼくは高校から社会人になって２年目に突入しました。', 'ちなみに妻も同じ会社で働いています。',
       '結婚生活も２年目に突入しました。', 'そんな妻の愛が強すぎて毎日が不安に陥ってます。', '私の名前は、。',
       '旧苗字は柴崎。', '私の毎日の朝は午前５時３０分に起床する。',
       '彼は何時も朝が弱いので私が起きてから３０分後くらいに起きてくる。',
       '私はまず、私と彼の分の朝御飯と昼食を作ることが日課になりました。', '彼は少食なのでそこまで料理をすることに時間はありません。',
       '朝御飯と昼食の準備が終えたら、起こしに行きます。', '彼には普通に起こしただけでは早々起きることがありません。',
       '仕方ないので毎日彼のお腹にダイブして起こすようにしています。',
       '彼は止めてほしいらしいけどこうでもしないと起きないのでこう方法を取ることにしました。',
       '彼とは同じ会社なので毎日一緒に通勤しています。', '親からのプレゼントでもらった車で毎日通勤しています。',
       '基本的には夜勤はしないから一緒に帰ることが出来る。', '彼とは会社内では滅多に会えない。',
       '彼はまだ若手で事務職の仕事は先輩方がやってしまうから色んな部署の手伝いにいっている。',
       '前にもっとちゃんとした仕事をしたいと言ってたな。', '私は会計のお仕事をしている。',
       'まぁ、嫌いじゃないから良いんですけど。', '今日は二人とも夜勤は無かったので今日の夕飯を買ってから家に帰りました。',
       'それからは、私は彼に甘えます。', 'ぼくの名前は、。', 'ぼくの朝は妻に起こされるところから始まる。',
       '毎日ダイブしてくるから勘弁してほしいよ。', 'でも、そうでもしないと起きないからそうでもしないと起きないんだけどね。',


In [17]:
data['Y_score'][positive_index]

array([0.3779645 , 0.33333334, 0.43643582, 0.33333334])

In [18]:
data['rouge']['f']

0.465116274094105