In [1]:
from keras_regression_extractive_summarizer import KerasRegressionExtractiveSummarizer

Using TensorFlow backend.


In [2]:
import numpy as np

In [3]:
summarizer = KerasRegressionExtractiveSummarizer()

loading embedding_model...
loading embedding_model...
loading similarity threshold data...
loading trained model: /Users/kiriyama.k.ab/Fujii.lab/story_modeling/model/narou/threshold_estimate_trained_model/180820/model_30_vloss0.0078.hdf5
loading data dict...
loading splited data ncode...
converting dict to tensor...
converting dict to tensor...
num of novels which is training data: 746
num of novels which is test data: 187
loading trained model: /Users/kiriyama.k.ab/Fujii.lab/story_modeling/model/narou/reg_trained_model/180817/model_26_vloss0.0058.hdf5


In [101]:
ncode = list(summarizer.data_dict.keys())[5]

In [102]:
data = summarizer.data_dict[ncode]

In [103]:
contents_lines = summarizer.corpus.get_contents_lines(ncode)

In [104]:
removed_contents_lines = np.array(summarizer.corpus.remove_error_line_indexes_from_contents_lines(contents_lines, data['error_line_indexes']))

In [105]:
synopsis_lines = summarizer.corpus.get_synopsis_lines(ncode)

In [106]:
positive_index = np.where(data['Y']==1)

In [107]:
negative_index = np.where(data['Y']==0)

In [108]:
positive_index

(array([  1,  10,  14,  15,  61, 102, 193, 416]),)

In [109]:
negative_index

(array([  0,   2,   3,   4,   5,   6,   7,   8,   9,  11,  12,  13,  16,
         17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,
         30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,
         43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
         56,  57,  58,  59,  60,  62,  63,  64,  65,  66,  67,  68,  69,
         70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,
         83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
         96,  97,  98,  99, 100, 101, 103, 104, 105, 106, 107, 108, 109,
        110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122,
        123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135,
        136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148,
        149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161,
        162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174,
        175, 176, 177, 178, 179, 180, 181, 182, 183

In [110]:
ncode

'n1185df'

In [111]:
synopsis_lines

['知識狂であり天才である彼は死後の世界が気になってしまい自殺してしまう。',
 'すると神と名乗る人物に人格を消されてしまって転生!?神界で起こる彼をめぐる騒動。',
 '彼の天才的な頭脳とその知識欲の秘密とは、どうして彼は転生させられたのか。',
 'そんな中彼は人格が消されたお陰で毎日平穏でハーレムな日々をすごす。']

In [112]:
removed_contents_lines[positive_index]

array(['彼は無機質のコンクリートの壁にもたれかけ冷たさを感じながら呟く。',
       '好奇心だけでなく彼の頭脳も凄く日本は彼のお陰でギリギリ国別特許取得数一位を取れ、平和憲法を変えなくて済んでいることが出来ているほどだ。',
       'すると彼は痙攣しながら倒れていく。', 'あっさり彼は死んだ。', 'それにしては感覚がおかしい気がするな。',
       'なので転生させたあと徐々にこの脳の記憶能力を拡張していると。', 'お家取り潰しになってしまうかもしれないからだ。',
       '盗賊は全員倒されてしまった。'], dtype='<U106')

In [113]:
removed_contents_lines[negative_index]

array(['シーンと一切音がしない暗闇の中少年はんでいた。',
       '「あー新しい公式や物質が見つからないのか！暇だ。何なら事件でも良い」彼はコンクリートの棺桶とも形容できるほどの粗末で壁紙すらない部屋に隔離されている。',
       '原因は彼の一般人、いや、小変人すら凌駕するほどの好奇心だ。',
       'それは恐ろしく、好奇心を満たすためには普通に犯罪を犯し、狂乱状態になった後に刑務所を脱獄(四回)するほど。',
       'そのことからこの部屋には彼をとどめておくために様々なものが用意されている。',
       'コンピューター、顕微鏡、はんだごて、それらを扱うために必要な電気を供給するコンセントやＬＡＮまでもが。',
       '本などはいえば貸してくれるほどだ。', '一般の受刑者のような懲役が彼に課されることはない。',
       '彼は極秘に兵器や家電、発明発見をすることでその懲役をしていることになっている。',
       'そんな彼がついに触れてはいけない謎に触れてしまった。',
       '「死んだ後の世界はどんな世界だ？」もちろん彼がこんなことに興味を持ってしまったらどうなるかは誰でもわかるだろう。',
       '「じゃあ死んでみるか」彼は支給されている爪きりでパソコンのコンセントをぶち切り、そのまま二つの銅線を両手を広げそれぞれの手で持った。',
       '「ここはどこだ」俺は真っ黒な壁を持つ部屋を見渡した。', '俺は死んだはずだ。', 'なのに意識はあり体は熱を持っている。',
       'そしてこの部屋照明が無いぞ。', 'たとえ照明が埋め込まれていたとしても光を透過すできる物質でないといけないため黒いわけがない。',
       'どういうことだ。', '俺の未知の物質か。', '面白い。', '自分でもわかるほどに口角がつりあがっていた。', 'ペタペタ。',
       '触り心地は滑々《すべすべ》しているな。', '思いっきりこぶしを叩きつけてみるか。', '「オリャッ！」',
       '「イタッ！くないぞ。それどころか感触も無い。そんなわけないだろ。力を跳ね返す物質なら俺の手が跳ね返っているはずだろ！？何でだ！ハッハッハッハー面白い、面白いぞこの物質。力

In [114]:
data['Y_score'][positive_index]

array([0.24494897, 0.25318483, 0.25819889, 0.2981424 , 0.23570225,
       0.23354967, 0.23570225, 0.24806947])

In [115]:
data['rouge']['f']

0.35460992423519944